package ytmusic

import (
	"fmt"

	"github.com/imroc/req/v3"
)

// YTMusic encapsulates all methods relating to YouTube Music.
type YTMusic struct {
	RequestClient *req.Client
	Config        Config
}

type InitialisationOpts struct {
	RequestClient       *req.Client
	BaseAPIURL          string
	AuthenticationToken string
}

type Config struct {
	BaseAPIURL          string
	AuthenticationToken string
}

// /////////////////////////////////////////////////
// API Types (Autogenerated)
// /////////////////////////////////////////////////
type ytmusicAPIGetPlaylistResponse struct {
	Data struct {
		Identifier  string `json:"identifier"`
		Description string `json:"description"`
		Title       string `json:"title"`
		Tracks      []struct {
			Artists    []string `json:"artists"`
			Identifier string   `json:"identifier"`
			Title      string   `json:"title"`
		} `json:"tracks"`
	} `json:"data"`
}

type ytmusicAPICreatePlaylistResponse struct {
	Data string `json:"data"`
}

type ytmusicAPISearchResponse struct {
	Data []struct {
		Artists    []string `json:"artists"`
		Category   string   `json:"category"`
		Identifier string   `json:"identifier"`
		ResultType string   `json:"result_type"`
		Title      string   `json:"title"`
	} `json:"data"`
}

type ytmusicAPIErrorResponse struct {
	Errors  []string `json:"errors"`
	Message string   `json:"message"`
}

func (e *ytmusicAPIErrorResponse) Error() string {
	return fmt.Sprintf("YTMusic API: message: %v  errors: %+v", e.Message, e.Errors)
}
