package spotify

import (
	"fmt"

	"github.com/imroc/req/v3"
)

type Spotify struct {
	RequestClient *req.Client
	Config        Config
}

type InitialisationOpts struct {
	RequestClient             *req.Client
	BaseAPIURL                string
	ClientID                  string
	UserID                    string
	ClientSecret              string
	AuthenticationURL         string
	AuthenticationRedirectURL string
}

type Config struct {
	BaseAPIURL                string
	UserID                    string
	ClientID                  string
	ClientSecret              string
	AuthenticationURL         string
	AuthenticationRedirectURL string
}

// API Types (Autogenerated).
type spotifyAPIGetPlaylistResponse struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Images      []struct {
		URL string `json:"url"`
	} `json:"images"`
	Tracks spotifyAPITracksResponse `json:"tracks"`
}

type spotifyAPITracksResponse struct {
	Next  string `json:"next"`
	Total int    `json:"total"`
	Items []struct {
		Track struct {
			ID      string `json:"id"`
			Name    string `json:"name"`
			Artists []struct {
				Name string `json:"name"`
			} `json:"artists"`
		} `json:"track"`
	} `json:"items"`
}

type spotifyAPISearchResponse struct {
	Tracks struct {
		Limit int    `json:"limit"`
		Next  string `json:"next"`
		Total int    `json:"total"`
		Items []struct {
			Artists []struct {
				Name string `json:"name"`
			} `json:"artists"`
			ID   string `json:"id"`
			Name string `json:"name"`
		} `json:"items"`
	} `json:"tracks"`
}

type spotifyAPICreatePlaylistResponse struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	URL  string `json:"uri"`
}

type spotifyAPIClientCredentialsResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int    `json:"expires_in"`
	TokenType   string `json:"token_type"`
}

type spotifyAPIBearerCredentialsResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresAt    int64  `json:"expires_at"`
}

type spotifyAPIRefreshTokenResponse struct {
	AccessToken string `json:"access_token"`
	TokenType   string `json:"token_type"`
	Scope       string `json:"scope"`
	ExpiresIn   int    `json:"expires_in"`
}

type spotifyAPIError struct {
	APIError struct {
		Status  uint   `json:"status"`
		Message string `json:"message"`
	} `json:"error"`
}

func (e *spotifyAPIError) Error() string {
	return fmt.Sprintf("Spotify API Error: status: %v  reason: %s", e.APIError.Status, e.APIError.Message)
}
