root = "."
testdata_dir = "testdata_waakye"
tmp_dir = "tmp_waakye"

[build]
  args_bin = []
  bin = "./tmp_waakye/main"
  cmd = "go build -o ./tmp_waakye/main cmd/waakye/main.go"
  delay = 0
  exclude_dir = ["assets", "tmp_waakye", "tmp_masa", "vendor", "testdata_waakye", "testdata_masa"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors-waakye.log"
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
