version: '3'
services:
  kilishi:
    image: kilishi
    ports:
      - "8000:8000"
    env_file:
      - ./kilishi/.env
    volumes:
      - kilishi-sqlite:/db.sqlite3
    depends_on:
      - redis_cache
      - masa
  masa:
    image: masa
    ports:
      - "5001:5001"
    env_file:
      - ./masa/.env

  redis_cache:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  kilishi-sqlite:
