name: Lint
on: [workflow_call, pull_request]
permissions:
  contents: read

jobs:
  lint_kilishi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./kilishi

  lint_shaki:
    needs: [lint_kilishi]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./shaki
