name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  linting:
    uses: ./.github/workflows/lint.yml

  generate_release:
    runs-on: ubuntu-latest
    needs: [linting]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: stable

      - uses: goreleaser/goreleaser-action@v4
        with:
          workdir: ./shaki
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
