# fly.toml app configuration file generated for asaro on 2023-05-30T16:52:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "asaro"
primary_region = "atl"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
